import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import NavBar from "./NavBar";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <div className="sticky top-0 left-0">
          <NavBar session={session as NonNullable<typeof session>} />
        </div>
        
        <main className="flex-1 flex flex-col mx-5">
          <div className="flex-1 py-3 bg-zinc-50 font-sans dark:bg-black">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
